export const IMAGES: Record<string, string> = {
    "Arduino UNO R3": "/products/arduino-uno-r3.jpg",
    "Breadboard 400 Points": "/products/breadboard-400-points.jpg",
    "Jumper Wires (Set of 40)": "/products/jumper-wires-set-of-40.jpg",
    "HC-SR04 Ultrasonic Sensor": "/products/hc-sr04-ultrasonic-sensor.jpg",
    "DHT11 Temperature & Humidity Sensor": "/products/dht11-temperature-humidity-sensor.jpg",
    "16x2 LCD Display": "/products/16x2-lcd-display.jpg",
    "ESP32 Development Board": "/products/esp32-development-board.jpg",
    "ESP8266 WiFi Module": "/products/esp8266-wifi-module.jpg",
    "Servo Motor SG90": "/products/servo-motor-sg90.jpg",
    "DC Motor (30 RPM)": "/products/dc-motor-30-rpm.jpg",
    "Relay Module 5V (1 Channel)": "/products/relay-module-5v-1-channel.jpg",
    "Motor Driver Module L298N": "https://raw.githubusercontent.com/hibit-dev/l298n-motor-driver/master/images/l298n-motor-driver-module-pinout.png",
    "Arduino Nano": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Arduino_Nano.jpg/320px-Arduino_Nano.jpg",
    "Arduino Mega 2560": "https://upload.wikimedia.org/wikipedia/commons/3/39/Arduino_Mega_2560.jpg",
    "Gyroscope MPU6050": "/products/gyroscope-mpu6050.jpg",
    "PIR Motion Sensor Module": "/products/pir-motion-sensor-module.jpg",
    "IR Receiver Module": "/products/ir-receiver-module.jpg",
    "Light Sensor (LDR) Module": "https://upload.wikimedia.org/wikipedia/commons/a/a2/LDR07_Light-dependent_CdS_photoresistor.jpg",
    "Soil Moisture Sensor": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Soil_moisture_sensor.JPG",
    "Flame Sensor Module": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flame-igniter%28top%29-and-flame-sensor.jpg/320px-Flame-igniter%28top%29-and-flame-sensor.jpg",
    "Sound Sensor Module": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Electronic_component_microphone.jpg/320px-Electronic_component_microphone.jpg",
    "Gas Sensor MQ-5": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Gas_sensor.jpg/320px-Gas_sensor.jpg",
    "Bluetooth Module HC-05": "/products/bluetooth-module-hc-05.jpg",
    "SIM800L GSM Module": "/products/sim800l-gsm-module.jpg",
    "Soldering Iron Kit": "/products/soldering-iron-kit.jpg",
    "OLED Display 0.96 Inch": "/products/oled-display-0-96-inch.jpg",
    "LEDs 5mm (Pack of 10)": "/products/leds-5mm-pack-of-10.jpg",
    "Resistor Pack (80 pcs)": "/products/resistor-pack-80-pcs.jpg",
    "Capacitor Pack (Mixed)": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Electronic-Component-Ceramic-Capacitor.jpg",
    "Buzzer (Active)": "/products/buzzer-active.jpg",
    "Push Button Switch": "/products/push-button-switch.jpg",
    "Diode 1N4007 (Pack of 10)": "https://upload.wikimedia.org/wikipedia/commons/2/23/Diode_1N4007.jpg",
    "Transistor BC547": "https://upload.wikimedia.org/wikipedia/commons/2/24/BC546B_transistor_%2801%29.jpg",
    "Potentiometer 10K": "https://upload.wikimedia.org/wikipedia/commons/b/b5/10k_Ohm_Breadboard_Compatible_Potentiometer.jpg",
    "7 Segment Display (1 Digit)": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Seven_segment_display_1_digit_%28red%29.svg/200px-Seven_segment_display_1_digit_%28red%29.svg.png",
    "Laser Module": "/products/laser-module.jpg",
    "Magnetic Reed Switch": "/products/magnetic-reed-switch.jpg",
    "Hall Effect Sensor": "/products/hall-effect-sensor.jpg",
    "Tilt Switch Module": "/products/tilt-switch-module.jpg",
    "PS2 Game Joystick Module": "/products/ps2-game-joystick-module.jpg",
    "Passive Buzzer Module": "/products/passive-buzzer-module.jpg",
    "LED Traffic Light Module": "/products/led-traffic-light-module.jpg",
    "Stepper Motor NEMA 17": "/products/stepper-motor-nema-17.jpg",
    "Power Supply Module 5V": "/products/power-supply-module-5v.jpg",
    "USB to Serial Converter": "/products/usb-to-serial-converter.jpg",
    "Multimeter (Digital)": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Digital_Multimeter_Aka.jpg",
    "IC 74HC595 Shift Register": "https://upload.wikimedia.org/wikipedia/commons/2/23/74HC595.jpg",
    "10K Sliding Potentiometer": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Mini_Star_416_-_Slide_potentiometer-2973.jpg",
    "Accelerometer ADXL345": "/products/accelerometer-adxl345.jpg",
    "I2C 16x2 LCD Module": "/products/i2c-16x2-lcd-module.jpg"
};
