export const IMAGES: Record<string, string> = {
    "Arduino UNO R3": "/products/arduino-uno-r3.jpg",
    "Breadboard 400 Points": "/products/breadboard-400-points.jpg",
    "Jumper Wires (Set of 40)": "/products/jumper-wires-set-of-40.jpg",
    "HC-SR04 Ultrasonic Sensor": "/products/hc-sr04-ultrasonic-sensor.jpg",
    "DHT11 Temperature & Humidity Sensor": "/products/dht11-temperature-humidity-sensor.jpg",
    "16x2 LCD Display": "/products/16x2-lcd-display.jpg",
    "ESP32 Development Board": "/products/esp32-development-board.jpg",
    "ESP8266 WiFi Module": "/products/esp8266-wifi-module.jpg",
    "Servo Motor SG90": "/products/servo-motor-sg90.jpg",
    "DC Motor (30 RPM)": "/products/dc-motor-30-rpm.jpg",
    "Relay Module 5V (1 Channel)": "/products/relay-module-5v-1-channel.jpg",
    "Motor Driver Module L298N": "/products/motor-driver-module-l298n.jpg",
    "Arduino Nano": "/products/arduino-nano.webp",
    "Arduino Mega 2560": "/products/arduino-mega-2560.jpeg",
    "Gyroscope MPU6050": "/products/gyroscope-mpu6050.jpg",
    "PIR Motion Sensor Module": "/products/pir-motion-sensor-module.jpg",
    "IR Receiver Module": "/products/ir-receiver-module.jpg",
    "Light Sensor (LDR) Module": "/products/light-sensor-module.jpg",
    "Soil Moisture Sensor": "/products/soil-sensor-module.jpg",
    "Flame Sensor Module": "/products/flame-sensor-module.jpg",
    "Sound Sensor Module": "/products/sound-sensor-module.jpg", // Note: Missing file
    "Gas Sensor MQ-5": "/products/gas-sensor-mq5.jpg",
    "Bluetooth Module HC-05": "/products/bluetooth-module-hc-05.jpg",
    "SIM800L GSM Module": "/products/sim800l-gsm-module.jpg",
    "Soldering Iron Kit": "/products/soldering-iron-kit.jpg",
    "OLED Display 0.96 Inch": "/products/oled-display-0-96-inch.jpg",
    "LEDs 5mm (Pack of 10)": "/products/leds-5mm-pack-of-10.jpg",
    "Resistor Pack (80 pcs)": "/products/resistor-pack-80-pcs.jpg",
    "Capacitor Pack (Mixed)": "/products/capacitor-mixed.jpg",
    "Buzzer (Active)": "/products/buzzer-active.jpg",
    "Push Button Switch": "/products/push-button-switch.jpg",
    "Diode 1N4007 (Pack of 10)": "/products/1n4007-diode-pack.webp",
    "Transistor BC547": "/products/bc547-transistor.webp", // Note: Missing file
    "Potentiometer 10K": "/products/potentiometer-10k.jpg",
    "7 Segment Display (1 Digit)": "/products/seven-segment-display-1-digit.png", // Note: Missing file
    "Laser Module": "/products/laser-module.jpg",
    "Magnetic Reed Switch": "/products/magnetic-reed-switch.jpg",
    "Hall Effect Sensor": "/products/hall-effect-sensor.jpg",
    "Tilt Switch Module": "/products/tilt-switch-module.jpg",
    "PS2 Game Joystick Module": "/products/ps2-game-joystick-module.jpg",
    "Passive Buzzer Module": "/products/passive-buzzer-module.jpg",
    "LED Traffic Light Module": "/products/led-traffic-light-module.jpg",
    "Stepper Motor NEMA 17": "/products/stepper-motor-nema-17.jpg",
    "Power Supply Module 5V": "/products/power-supply-module-5v.jpg",
    "USB to Serial Converter": "/products/usb-to-serial-converter.jpg",
    "Multimeter (Digital)": "/products/multimeter-digital.jpg",
    "IC 74HC595 Shift Register": "/products/ic74hc595-shift-register.jpeg",
    "10K Sliding Potentiometer": "/products/sliding-potentiometer.jpg",
    "Accelerometer ADXL345": "/products/accelerometer-adxl345.jpg",
    "I2C 16x2 LCD Module": "/products/i2c-16x2-lcd-module.jpg"
};
